{include file="sections/header.tpl"}
<style>{literal}.olt-card{border-radius:10px;overflow:hidden;box-shadow:0 5px 16px rgba(30,50,80,.12)}.olt-table td{vertical-align:middle!important}.olt-actions .btn,.olt-actions form{display:inline-block;margin:2px}.olt-meta{font-size:12px;color:#6b778c}.olt-health{min-width:190px}.olt-health .label{display:inline-block;margin:2px}{/literal}</style>
<div class="row"><div class="col-md-12"><h3 style="margin-top:0"><i class="fa fa-server text-primary"></i> OLT Management <small>Devices, connectivity, sync and ONU access</small><a class="btn btn-primary pull-right" href="{Text::url('olts/add')}"><i class="fa fa-plus"></i> Add OLT</a></h3></div>
<div class="col-md-4"><div class="small-box bg-aqua olt-card"><div class="inner"><h3>{$olts|@count}</h3><p>Total OLT</p></div><div class="icon"><i class="fa fa-server"></i></div></div></div><div class="col-md-4"><div class="small-box bg-green olt-card"><div class="inner"><h3>{$total_online|default:0}</h3><p>Online ONU</p></div><div class="icon"><i class="fa fa-signal"></i></div><a href="{Text::url('onus/online')}" class="small-box-footer">View Online ONU <i class="fa fa-arrow-circle-right"></i></a></div></div><div class="col-md-4"><div class="small-box bg-purple olt-card"><div class="inner"><h3>{$total_onu|default:0}</h3><p>Total Discovered ONU</p></div><div class="icon"><i class="fa fa-sitemap"></i></div><a href="{Text::url('onus')}" class="small-box-footer">View All ONU <i class="fa fa-arrow-circle-right"></i></a></div></div></div>
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-list"></i> OLT List</h3></div><div class="box-body table-responsive"><table class="table table-bordered table-striped table-hover olt-table"><thead><tr><th>OLT</th><th>Management</th><th>Connection</th><th>ONU Health</th><th>Last Sync</th><th>Essential Controls</th></tr></thead><tbody>{foreach $olts as $o}<tr>
<td><b>{$o['name']|escape}</b><br><span class="olt-meta">{$o['vendor']|escape} {$o['model']|escape}</span><br><span class="olt-meta"><i class="fa fa-map-marker"></i> {$o['location']|default:'No location'|escape}</span></td>
<td><code>{$o['management_host']|escape}:{$o['port']}</code><br><span class="olt-meta">{$o['protocol']|upper}{if $o['management_vlan']} &bull; VLAN {$o['management_vlan']|escape}{/if}</span></td>
<td>{if $o['status']=='Online'}<span class="label label-success"><i class="fa fa-check-circle"></i> Online</span>{elseif $o['status']=='Offline'}<span class="label label-danger"><i class="fa fa-times-circle"></i> Offline</span>{else}<span class="label label-default">{$o['status']|escape}</span>{/if}<br><small class="olt-meta">Sync: {$o['last_sync_status']|default:'never'|escape}</small></td>
<td class="olt-health"><span class="label label-primary">Total {$o['onu_count']}</span><span class="label label-success">Online {$o['online_count']}</span><span class="label label-default">Offline {$o['offline_count']}</span>{if $o['los_count']>0}<span class="label label-danger">LOS {$o['los_count']}</span>{/if}{if $o['unassigned_count']>0}<span class="label label-warning">Unassigned {$o['unassigned_count']}</span>{/if}</td>
<td>{$o['last_sync_at']|default:'Never'|escape}{if $o['last_sync_error']}<br><small class="text-danger" title="{$o['last_sync_error']|escape}">Last sync failed</small>{/if}</td>
<td class="olt-actions"><a class="btn btn-xs btn-primary" href="{Text::url('onus')}&olt_id={$o['id']}"><i class="fa fa-sitemap"></i> View ONUs</a><form method="post" action="{Text::url('olts/test')}"><input type="hidden" name="token" value="{$csrf_token}"><input type="hidden" name="id" value="{$o['id']}"><button class="btn btn-xs btn-info"><i class="fa fa-plug"></i> Test</button></form><form method="post" action="{Text::url('olts/sync')}"><input type="hidden" name="token" value="{$csrf_token}"><input type="hidden" name="id" value="{$o['id']}"><button class="btn btn-xs btn-success" onclick="return confirm('Sync this OLT now?')"><i class="fa fa-refresh"></i> Sync</button></form><a class="btn btn-xs btn-default" href="{Text::url('olts/edit/', $o['id'])}"><i class="fa fa-pencil"></i> Edit</a>{if $o['onu_count']==0}<form method="post" action="{Text::url('olts/delete')}" onsubmit="return confirm('Delete this OLT?')"><input type="hidden" name="token" value="{$csrf_token}"><input type="hidden" name="id" value="{$o['id']}"><button class="btn btn-xs btn-danger"><i class="fa fa-trash"></i> Delete</button></form>{/if}<br><a class="btn btn-xs btn-success" href="{Text::url('onus/online')}&olt_id={$o['id']}">Online</a><a class="btn btn-xs btn-warning" href="{Text::url('onus/offline')}&olt_id={$o['id']}">Offline</a><a class="btn btn-xs btn-danger" href="{Text::url('onus/los')}&olt_id={$o['id']}">LOS</a><a class="btn btn-xs btn-default" href="{Text::url('onus/unassigned')}&olt_id={$o['id']}">Unassigned</a></td>
</tr>{foreachelse}<tr><td colspan="6" class="text-center text-muted" style="padding:30px">No OLT configured. Click Add OLT to get started.</td></tr>{/foreach}</tbody></table></div></div>
{include file="sections/footer.tpl"}
