<?php
/** OLT access boundary; only the verified V-SOL Telnet adapter is enabled. */
class OltManager {
    // Read the existing persistent key used by the active OLT sync adapter.
    // Never create a replacement key: it would make stored credentials unreadable.
    private static function key(){
        $file='/www/wwwroot/27.147.201.165/system/secure/olt-encryption.key';
        $key=@file_get_contents($file);
        if($key===false||strlen($key)!==32)throw new Exception('OLT encryption key is unavailable');
        return $key;
    }
    public static function encrypt($value){$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($value,'aes-256-gcm',self::key(),OPENSSL_RAW_DATA,$iv,$tag);return base64_encode($iv.$tag.$cipher);}
    public static function decrypt($value){$raw=base64_decode((string)$value,true);if($raw===false||strlen($raw)<29)throw new Exception('Stored OLT credential is invalid');$plain=openssl_decrypt(substr($raw,28),'aes-256-gcm',self::key(),OPENSSL_RAW_DATA,substr($raw,0,12),substr($raw,12,16));if($plain===false)throw new Exception('Stored OLT credential cannot be decrypted');return $plain;}
    public static function validHost($host){return (bool)filter_var($host,FILTER_VALIDATE_IP)||(bool)preg_match('/^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i',$host);}
    private static function supported($olt){return strtolower((string)$olt['vendor'])==='vsol'&&strtolower((string)$olt['protocol'])==='telnet';}
    private static function read($socket,$until,$seconds=8){$out='';$end=microtime(true)+$seconds;while(microtime(true)<$end){$part=fread($socket,8192);if($part!==false)$out.=$part;if(stripos($out,$until)!==false)break;usleep(100000);}return $out;}
    private static function vsol($olt,$command){$socket=@fsockopen($olt['management_host'],(int)$olt['port'],$errno,$error,8);if(!$socket)throw new Exception($errno===110?'Timeout':'Connection Failed');stream_set_timeout($socket,1);$banner=self::read($socket,'Username:',8);if(stripos($banner,'Username:')===false){fclose($socket);throw new Exception('Unsupported Protocol');}fwrite($socket,(string)$olt['username']."\r\n");$password=self::read($socket,'Password:',8);if(stripos($password,'Password:')===false){fclose($socket);throw new Exception('Authentication Failed');}fwrite($socket,self::decrypt($olt['encrypted_password'])."\r\n");$login=self::read($socket,'epon#',10);if(stripos($login,'epon#')===false){fclose($socket);throw new Exception('Authentication Failed');}if($command===''){fclose($socket);return '';}fwrite($socket,$command."\r\n");$output=self::read($socket,'epon#',12);fclose($socket);return $output;}
    public static function test($olt){if(!self::validHost($olt['management_host'])||!self::supported($olt))return ['status'=>'Unsupported Protocol'];try{self::vsol($olt,'');return ['status'=>'Connected'];}catch(Throwable $e){return ['status'=>in_array($e->getMessage(),['Timeout','Connection Failed','Authentication Failed','Unsupported Protocol'],true)?$e->getMessage():'Connection Failed'];}}
    private static function pon($oltId,$port,$now){$pon=ORM::for_table('tbl_olt_pon_ports')->where('olt_id',$oltId)->where('slot_number','1')->where('port_number',(string)$port)->find_one();if(!$pon){$pon=ORM::for_table('tbl_olt_pon_ports')->create();$pon->olt_id=$oltId;$pon->slot_number='1';$pon->port_number=(string)$port;$pon->created_at=$now;}$pon->name='PON 1/'.$port;$pon->status='ONLINE';$pon->updated_at=$now;$pon->save();return $pon;}
    private static function syncLog($oltId,$started){try{$log=ORM::for_table('tbl_olt_sync_logs')->create();$log->olt_id=$oltId;$log->started_at=$started;$log->status='running';$log->onu_found=0;$log->onu_updated=0;$log->new_onu=0;$log->moved_onu=0;$log->save();return $log;}catch(Throwable $e){return null;}}
    public static function sync($olt){if(!self::supported($olt))throw new Exception('Unsupported operation for this vendor/protocol');$started=date('Y-m-d H:i:s');$log=self::syncLog($olt['id'],$started);try{$all=self::vsol($olt,'show olt 1 all-onu-info');$online=self::vsol($olt,'show olt 1 online-onu');$optical=self::vsol($olt,'show olt 1 optical-online-onu');$distance=[];$power=[];preg_match_all('/^\s*(\d+)\s+(\d+)\s+([0-9a-f-]{17})\s+\S+\s+\S+\s+(\d+)\s*/mi',$online,$matches,PREG_SET_ORDER);foreach($matches as $row)$distance[$row[1].'/'.$row[2]]=(float)$row[4];preg_match_all('/^\s*(\d+)\s+(\d+)\s+([0-9a-f-]{17})\s+\S+\s+(-?[\d.]+)\s+(-?[\d.]+)/mi',$optical,$matches,PREG_SET_ORDER);foreach($matches as $row)$power[$row[1].'/'.$row[2]]=[(float)$row[4],(float)$row[5]];preg_match_all('/^\s*(\d+)\s+(\d+)\s+([0-9a-f-]{17})\s+(\S+)/mi',$all,$matches,PREG_SET_ORDER);$now=date('Y-m-d H:i:s');$found=0;$new=0;$moved=0;foreach($matches as $row){$port=(string)$row[1];$onuNo=(string)$row[2];$key=$port.'/'.$onuNo;$mac=strtoupper(str_replace('-',':',$row[3]));$pon=self::pon($olt['id'],$port,$now);$onu=ORM::for_table('tbl_onus')->where('olt_id',$olt['id'])->where('mac_address',$mac)->find_one();$isNew=!$onu;if(!$onu){$onu=ORM::for_table('tbl_onus')->create();$onu->created_at=$now;$new++;}$oldStatus=(string)$onu->status;$oldLocation=(string)$onu->pon_port.'/'.$onu->onu_id;$status=strtolower($row[4])==='online'?'ONLINE':(strtolower($row[4])==='powerdown'?'OFFLINE':'UNKNOWN');$onu->olt_id=$olt['id'];$onu->pon_port_id=$pon->id;$onu->slot_number='1';$onu->pon_port=$port;$onu->onu_id=$onuNo;$onu->mac_address=$mac;$onu->status=$status;if(isset($distance[$key]))$onu->distance=$distance[$key];if(isset($power[$key])){$onu->tx_power=$power[$key][0];$onu->rx_power=$power[$key][1];}$onu->last_seen=$now;if($status==='ONLINE')$onu->last_online_at=$now;else $onu->last_offline_at=$now;$onu->updated_at=$now;$onu->save();if(!$isNew&&$oldLocation!==$port.'/'.$onuNo)$moved++;if($isNew||$oldStatus!==$status){$history=ORM::for_table('tbl_onu_status_logs')->create();$history->onu_id=$onu->id;$history->previous_status=$isNew?null:$oldStatus;$history->status=$status;$history->recorded_at=$now;$history->save();}if(isset($power[$key])){$history=ORM::for_table('tbl_onu_power_logs')->create();$history->onu_id=$onu->id;$history->rx_power=$onu->rx_power;$history->tx_power=$onu->tx_power;$history->recorded_at=$now;$history->save();}$found++;}if($log){$log->finished_at=date('Y-m-d H:i:s');$log->status='success';$log->onu_found=$found;$log->onu_updated=$found;$log->new_onu=$new;$log->moved_onu=$moved;$log->save();}return ['found'=>$found,'new'=>$new,'moved'=>$moved];}catch(Throwable $e){if($log){$log->finished_at=date('Y-m-d H:i:s');$log->status='failed';$log->error_message=substr($e->getMessage(),0,255);$log->save();}throw $e;}}
}
