{include file="sections/header.tpl"}
<style>{literal}.ownership-card{border-radius:10px;box-shadow:0 5px 16px rgba(30,50,80,.12);overflow:hidden}.ownership-actions .btn{margin:2px}.ownership-toolbar{padding:15px;background:#f7f9fc;border:1px solid #e1e7ef;border-radius:8px;margin-bottom:15px}{/literal}</style>
<div class="row"><div class="col-md-12"><h3 style="margin-top:0"><i class="fa fa-object-group text-primary"></i> Customers &amp; Ownership <small>Assign, transfer and manage customers</small></h3></div>
<div class="col-lg-3 col-sm-6"><div class="small-box bg-aqua ownership-card"><div class="inner"><h3>{$ownership_main_count}</h3><p>Main ISP Customers</p></div><div class="icon"><i class="fa fa-building"></i></div><a href="{Text::url('reseller/ownership')}&owner=main" class="small-box-footer">View customers <i class="fa fa-arrow-circle-right"></i></a></div></div>
<div class="col-lg-3 col-sm-6"><div class="small-box bg-purple ownership-card"><div class="inner"><h3>{$ownership_reseller_count}</h3><p>Reseller Customers</p></div><div class="icon"><i class="fa fa-users"></i></div><a href="{Text::url('reseller/ownership')}&owner=reseller" class="small-box-footer">View customers <i class="fa fa-arrow-circle-right"></i></a></div></div>
<div class="col-lg-3 col-sm-6"><div class="small-box bg-green ownership-card"><div class="inner"><h3>{$ownership_active_count}</h3><p>Active Reseller Services</p></div><div class="icon"><i class="fa fa-check-circle"></i></div><a href="{Text::url('reseller/ownership')}&owner=reseller&status=Active" class="small-box-footer">View active <i class="fa fa-arrow-circle-right"></i></a></div></div>
<div class="col-lg-3 col-sm-6"><div class="small-box bg-yellow ownership-card"><div class="inner"><h3>{$ownership_pending_count}</h3><p>Pending Approval</p></div><div class="icon"><i class="fa fa-clock-o"></i></div><a href="{Text::url('reseller/ownership')}&owner=reseller&approval=pending" class="small-box-footer">Review pending <i class="fa fa-arrow-circle-right"></i></a></div></div></div>

<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-filter"></i> Customer Ownership Directory</h3></div><div class="box-body">
<form class="ownership-toolbar" method="get" action="{Text::url('reseller/ownership')}"><input type="hidden" name="_route" value="reseller/ownership"><div class="row"><div class="col-md-3"><input class="form-control" name="search" value="{$ownership_search|escape}" placeholder="Name, username, phone, PPPoE"></div><div class="col-md-3"><select class="form-control" name="owner"><option value="all">All ownership</option><option value="main" {if $ownership_owner=='main'}selected{/if}>Main ISP</option><option value="reseller" {if $ownership_owner=='reseller'}selected{/if}>All resellers</option>{foreach $resellers as $r}<option value="{$r['id']}" {if $ownership_owner==$r['id']}selected{/if}>{$r['name']|escape}</option>{/foreach}</select></div><div class="col-md-2"><select class="form-control" name="status"><option value="all">All status</option>{foreach $statuses as $st}<option value="{$st}" {if $ownership_status==$st}selected{/if}>{$st}</option>{/foreach}</select></div><div class="col-md-2"><select class="form-control" name="approval"><option value="all">All approval</option><option value="pending" {if $ownership_approval=='pending'}selected{/if}>Pending</option><option value="approved" {if $ownership_approval=='approved'}selected{/if}>Approved</option></select></div><div class="col-md-2"><button class="btn btn-primary btn-block"><i class="fa fa-search"></i> Filter</button></div></div></form>

<form method="post" action="{Text::url('reseller/ownership-bulk')}" id="ownershipBulk"><input type="hidden" name="csrf_token" value="{$csrf_token}"><div class="row" style="margin-bottom:12px"><div class="col-md-3"><select class="form-control" name="operation" id="ownershipOperation"><option value="assign">Assign / Transfer selected</option><option value="unassign">Return selected to Main ISP</option></select></div><div class="col-md-4"><select class="form-control select2" name="reseller_id" id="ownershipReseller"><option value="">Choose target reseller</option>{foreach $resellers as $r}{if $r['status']=='active'}<option value="{$r['id']}">{$r['name']|escape}</option>{/if}{/foreach}</select></div><div class="col-md-3"><button class="btn btn-info" onclick="return confirm('Apply ownership change to selected customers?')"><i class="fa fa-exchange"></i> Apply to Selected</button></div></div>
<div class="table-responsive"><table class="table table-bordered table-striped table-hover"><thead><tr><th><input type="checkbox" id="ownershipSelectAll"></th><th>Customer</th><th>Contact</th><th>Current Owner</th><th>Package / Expiry</th><th>Balance</th><th>Status</th><th>Approval</th><th>Manage</th></tr></thead><tbody>{foreach $ownership_rows as $c}<tr><td><input type="checkbox" name="customer_ids[]" value="{$c['id']}"></td><td><b>{$c['fullname']|escape}</b><br><small>{$c['username']|escape}{if $c['pppoe_username']} / {$c['pppoe_username']|escape}{/if}</small></td><td>{$c['phonenumber']|escape}<br><small>{$c['email']|escape}</small></td><td>{if $c['reseller_id']}<span class="label label-primary">{$c['reseller_name']|escape}</span>{else}<span class="label label-default">Main ISP</span>{/if}</td><td>{$c['active_package']|escape}{if $c['package_expiry']}<br><small>{$c['package_expiry']|escape}</small>{/if}</td><td>{Lang::moneyFormat($c['balance'])}</td><td><span class="label {if $c['status']=='Active'}label-success{else}label-default{/if}">{$c['status']|escape}</span></td><td>{if $c['reseller_id']}{if $c['approval_status']=='pending'}<span class="label label-warning">Pending</span>{else}<span class="label label-success">Approved</span>{/if}{else}-{/if}</td><td class="ownership-actions"><a class="btn btn-success btn-xs" href="{Text::url('customers/view/')}{$c['id']}">View</a><a class="btn btn-info btn-xs" href="{Text::url('customers/edit/')}{$c['id']}&token={$csrf_token}">Edit</a><a class="btn btn-primary btn-xs" href="{Text::url('plan/recharge/')}{$c['id']}&token={$csrf_token}">Recharge</a>{if $c['reseller_id'] && $c['approval_status']=='pending'}<button type="submit" class="btn btn-warning btn-xs" formaction="{Text::url('reseller/ownership-approve')}" name="customer_id" value="{$c['id']}">Approve</button>{/if}</td></tr>{foreachelse}<tr><td colspan="9" class="text-center text-muted">No customers match the selected filters.</td></tr>{/foreach}</tbody></table></div></form>
</div></div>
{literal}<script>$('#ownershipSelectAll').on('change',function(){$('#ownershipBulk input[name="customer_ids[]"]').prop('checked',this.checked);});$('#ownershipOperation').on('change',function(){$('#ownershipReseller').prop('disabled',this.value==='unassign');}).trigger('change');</script>{/literal}
{include file="sections/footer.tpl"}
